### ISSUE TITLE
Etherpad breaking when trying to export2html pad with a table

### ISSUE THREAD

**Issue by muppeth** [seballot/ep_tables2#24]
Noticed that if you try to export pad to html when it consists a table, it will break etherpad with the following:
 ```
[2017-06-29 03:03:44.657] [ERROR] console - TypeError: Cannot read property '1' of undefined
    at Object.exports.getLineHTMLForExport [as hook_fn] (/var/www/etherpad-lite/node_modules/ep_tables2/export2html.js:7:57)
    at normalizedhook (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:76:14
    at Function._.map._.collect (/var/www/etherpad-lite/src/node_modules/underscore/underscore.js:172:24)
    at Object.exports.callAll (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:75:24)
    at Object.exports.callAllStr (/var/www/etherpad-lite/src/static/js/pluginfw/hooks.js:122:27)
    at getHTMLFromAtext (/var/www/etherpad-lite/src/node/utils/ExportHtml.js:454:39)
    at /var/www/etherpad-lite/src/node/utils/ExportHtml.js:57:12
    at fn (/var/www/etherpad-lite/src/node_modules/async/lib/async.js:641:34)

**Comment by Clindbergh** [comment]
Hi
Here ##21 The author says he's not maintaining this repo any longer. I myself am afraid I am not able to help out with your problem since I'm stuck with #21. Could you tell me which version on which server and which npm version you're running so I might be able to work around #21.
Thanks.

**Comment by seballot** [comment]
Export seem to be fixed now
